### ISSUE TITLE
UNK position

### ISSUE THREAD

**Issue by lark047** [BurntSushi/nfldb#109]
I'm trying to use NFLDB for my fantasy league's scoring. In comparing fantasy points as calculated by ESPN to the Python script I wrote to use NFLDB, I get 0 points for Randy Bullock in week 1 instead of 7. I found that the issue is that his current position is UNK.

When does the position update to UNK happen? I understand that UNK is a valid value for 'team' when a player is cut from a roster, but wouldn't it make more sense to leave the position as whatever it was when the player was last on a team?

It seems to me that a player, especially an offensive player, still has a well-defined position even in free agency.

    nfldb=> select player_id, team, position from player where full_name = 'Randy Bullock';
     player_id  | team | position
    ------------+------+----------
     00-0029421 | UNK  | UNK
    (1 row)
    
    nfldb=>

Bullock was cut by the Texans on 9/29, but he played in weeks 1-3, kicking 5 FG and 3 PATs. Querying by name and position returns an empty set:

```Python
>>> import nfldb
>>> db = nfldb.connect()
>>> q = nfldb.Query(db)
>>> q.game(season_year = 2015, season_type = 'Regular', week = 1)
<nfldb.query.Query object at 0xb66876cc>
>>> q.player(full_name = 'Randy Bullock', position = 'K')
<nfldb.query.Query object at 0xb66876cc>
>>> print 'FGM FGA PAT'
FGA FGM PAT
>>> for stat in q.as_aggregate():
...   print st
...
>>>
```

What's the preferred method of querying for player stats in a given game? The method shown above doesn't work for players who are no longer on a team.

**Comment by BurntSushi** [comment]
The position data comes from here: https://raw.githubusercontent.com/BurntSushi/nflgame/master/nflgame/players.json

My guess is that the player data got corrupted at some point. Player data is flaky and inconsistent, and frankly, probably shouldn't be relied upon. Notably, player meta data such as position is *scraped* from NFL.com. Instead, you should identify players by their underlying identifiers (player name + position is not guaranteed to be unique).

You might be able to fix this particular issue by deleting the `Randy Bullock` entry from nflgame's players.json file, then run `nflgame-update-players --week 1`, and finally run `nfldb-update` again. The player data should stick at that point.

There is really nothing in the system that says how a player's position is determined. For the most part, it's determined in the script that scrapes player data: https://github.com/BurntSushi/nflgame/blob/master/nflgame/update_players.py

There are various heuristics in the scraping code that prevent it from hitting NFL.com too many times because that would be bad. This intrinsically implies that there are occasions when it is too conservative.

**Comment by lark047** [comment]
I removed him from players.json and ran `nflgame-update-players --week 1`. I see now that the file was updated:


    andrew@asimov:/usr/local/lib/python2.7/dist-packages$ grep -C 10 "Randy Bullock" ./nflgame/players.json | grep position
            "position": "K",
    andrew@asimov:/usr/local/lib/python2.7/dist-packages$ 

but `nfldb-update` didn't update his player record

    nfldb=> select player_id, team, position from player where full_name = 'Randy Bullock';
     player_id  | team | position
    ------------+------+----------
     00-0029421 | UNK  | UNK
    (1 row)
    
    nfldb=>

do I need to delete the record first?

**Comment by BurntSushi** [comment]
@lark047 Try `nfldb-update --player-interval 0` to force a player update.

**Comment by lark047** [comment]
I tried it. The command completed successfully but Bullock was still listed as UNK in the database. I updated the record myself and will close this issue.
