### ISSUE TITLE
Stadium and alternate profile id columns request

### ISSUE THREAD

**Issue by andr3w321** [BurntSushi/nfldb#118]
Would it be possible to add a stadium column to game and an alternate profile id field to the player field?  Something like

```
ALTER table game ADD COLUMN stadium VARCHAR(80);
ALTER table player ADD COLUMN alt_profile_id VARCHAR(12);
```

I am scraping stadium data from http://www.nfl.com/teams/schedule?team=CAR and injury data from http://www.nfl.com/teams/injuries?team=CAR  I can do it with

```
CREATE table gsis_id_stadium(
    gsis_id gameid REFERENCES game(gsis_id),
    stadium VARCHAR(30),
    PRIMARY KEY(gsis_id, stadium)
);

CREATE table profile_id_alt_profile_id(
    profile_id INTEGER REFERENCES player(profile_id),
    alt_profile_id VARCHAR(12),
    PRIMARY KEY(profile_id,alt_profile_id)
);
```

But doing all the join commands is annoying when querying and I would like to stay compatible with your version of nfldb by not modifying any tables only adding them if possible.  Thx.

**Comment by BurntSushi** [comment]
No, sorry. I'm not in favor of adding more meta data to `nfldb` because it requires more scraping maintenance, which is really not something I want to spend my time doing.

You could stay reasonably compatible with `nfldb` even with your own modifications by implementing a simplistic migration scheme. You couldn't reuse the one that exists in `nfldb`, but you certainly could copy it. Really all you'd have to do is use a different way to signal the version so that your database would have two versions attached to it: the upstream `nfldb` version and your own personal custom versioning.

Failing that, just write the joins.

**Comment by andr3w321** [comment]
Understandable.  Was worth a shot :)   I'll stick with the joins I suppose.
