### ISSUE TITLE
Can't install nfldb on mac

### ISSUE THREAD

**Issue by ealco9** [BurntSushi/nfldb#148]
I'm pretty new to this, I've managed to install Postgresql as well as create the database according to the instructions but when I get to the installation of the python package I get the following error:

error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted

And of course nothing is getting installed.

The command I'm using is: sudo pip install nfldb

Any help will be much appreciated

**Comment by BurntSushi** [comment]
@ealco9 If you fixed your issue, posting how you fixed it will help others.

**Comment by jasonlttl** [comment]
This is my first time using python, but I believe the issue is that certain system folders on OSX cannot be modified, even as root. It's possible to work around this, but a better solution may be to install a user modifiable python instance with homebrew.

This is explained more here.
http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade
