### ISSUE TITLE
Position for Free Agents is UNK

### ISSUE THREAD

**Issue by linkinpaak** [BurntSushi/nfldb#165]
After updating nfldb, free agents such as Arian Foster and Marshawn Lynch have had their positions updated to UNK.  I don't think players' positions should be updated just because they haven't signed with a team yet.

**Comment by BurntSushi** [comment]
The code that scrapes "global" player data from NFL.com is here: https://github.com/BurntSushi/nflgame/blob/master/nflgame/update_players.py

If there's a way to get the player's position even if they aren't assigned to a team (**in a way that scales**), then I'd be fine with that. But in general, the `player` table models players who are currently assigned to a team and it really doesn't have any memory other than the fact that player entries aren't deleted.

**Comment by linkinpaak** [comment]
It seems like the issue is that the code just scans the roster pages on nfl.com and players like Foster and Lynch are no longer on rosters, is that correct?  Because if I navigate to their player pages the title still has them listed as RBs.  I'll put some thought into it, but it would be far easier to solve this inside a database because you could stage the latest player data to a temp table then left join your existing player pool to the temp table and scan nfl.com for their position based on the player page url in the db for players not in the temp table.

**Comment by BurntSushi** [comment]
Right. The reason why I didn't hit the player page directly is because that requires an HTTP request for every single player. With the current approach, we only require an HTTP request for every team to do a complete player update. An important aspect of this project is staying under the radar and being respectful of resources that aren't ours. Distributing a script that periodically makes thousands of HTTP requests would not be wise. This is what I meant by "in a way that scales."

**Comment by BrutalSimplicity** [comment]
Why not just hit the player page when you come upon a player whom you have no position information for?

**Comment by BurntSushi** [comment]
Because there are almost as many `UNK` players as not:

```
[andrew@Liger ~] psql nfldb -c "select count(*) from player where position = 'UNK';"
 count 
-------
  4660
(1 row)

[andrew@Liger ~] psql nfldb -c "select count(*) from player;"
 count 
-------
  6744
(1 row)
```
