### ISSUE TITLE
2016 Schedule

### ISSUE THREAD

**Issue by DylanModesitt** [BurntSushi/nfldb#170]
How can I get the 2016 schedule? 

running

```
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2016, season_type='Regular', week=1)

for game in q.as_games():
    print game
```

yields nothing. Will the schedule automatically become available?

I tried `pip install --upgrade nfldb ` and `pip install --upgrade nflgame ` (even though I am pretty sure an nfldb update also updates nflgame. I also did a `python ./update_sched.py --rebuild` and a `python ./update_sched.py --rebuild --year 2016`.  I then did `nfldb-update` and `nfldb-update --update-schedule`

Is doing the modification @ochawkeye described <a href="https://github.com/BurntSushi/nfldb/issues/161"> here </a> still necessary? Or am I doing something else wrong?

**Comment by DylanModesitt** [comment]
@BurntSushi Any ideas? The season is coming close to starting up.

**Comment by DylanModesitt** [comment]
If anyone else was having this issue I had to do a:
`python update_sched.py --year 2016 --phase REG`
which caused this error on `nfldb-update`:
`DETAIL:  Key (pos_team)=(LA) is not present in table "team".`
so I performed the following query in postgres:
`INSERT INTO team VALUES ('LA', 'Los Angeles', 'Rams');`
and then `nfldb-update` had all the data.

**Comment by expectopatronum** [comment]
The downloaded games with the LA Rams now contain "UNK" instead of "LA". I try now to add a line to team.py. Hopefully it does not break anything if there are two entries for the rams.

**Comment by DylanModesitt** [comment]
I saw that too. I would like to know where "unk" which I assume stands for "unknown" comes from. I think this could be fixed with some additional psql query. Maybe @BurntSushi knows the best way.

**Comment by DylanModesitt** [comment]
Maybe a migration is required?

**Comment by hpadmanabhan** [comment]
@DylanModesitt and @expectopatronum please take the time to go through existing issues before opening up duplicates for things already addressed elsewhere.
Interim solutions to the 2016 schedule update and LA Rams change have already been provided on multiple issues here that don't require you to wait for an nfldb update from @BurntSushi.

**Comment by danielcroona** [comment]
You should edit the files nfldb/team.py and nflgame/init.py, and add the following line:
['LA', 'Los Angeles', 'Rams', 'Los Angeles Rams'],

On my machine the location for these files are:
/usr/local/lib/python2.7/dist-packages/nfldb/team.py
/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py

**Comment by expectopatronum** [comment]
@hpadmanabhan sorry I looked at all issues that had a relevant title. 

@danielcroona and this works? doesn't it matter that there is already an entry with "Rams"? Would it be possible to just replace 'STL' everywhere with 'LA' and then replace the old entry completely?

**Comment by hpadmanabhan** [comment]
@danielcroona My mistake in assuming folks understand what a relative path is. I provided paths relative to the packages there leaving out the preceding bits precisely because they can be different depending on your installation, but those are the relevant files.

Also, feel free to try out changes and see what happens, thats the fun with open source. At worst you'll need delete and start over.

**Comment by hpadmanabhan** [comment]
@expectopatronum no apologies needed, things don't often have the exact titles but when dealing with open source stuff its always good to check a little deeper first before putting up new issues out of courtesy to the main authors as their precious free time spent on these open source projects out of their generosity would be better spent on improving stuff than dealing with repeated queries.

With reference to the Rams, these are 2 different teams, replacing 'STL' with 'LA' will lose you all the history for 'STL Rams' since all the DB references will get switched. All historical data needs to continue to be associated with 'STL Rams' and new stuff needs to be associated with 'LA Rams'. 
Particularly important with nfldb that changes be idempotent since you should be able to drop and recreate the database if needed.

**Comment by DylanModesitt** [comment]
@hpadmanabhan I searched through docs. Did not see you referenced an issue in another repository.

**Comment by daweber** [comment]
@hpadmanabhan While I appreciate your "moderating" of this issue. posting things like "already addressed elsewhere." and "from where he picked out that snippet." without posting links is kind of useless to anyone.

Can someone please answer the following question:

What does one have to do to get the 2016-2017 Season to be included in an nfldb-update call?

Thanks

**Comment by BurntSushi** [comment]
> What does one have to do to get the 2016-2017 Season to be included in an nfldb-update call?

Short of digging it and fixing a few issues (nflgame schedule update, team name updates, maybe some other things), you'll need to wait for me to push out a new release. I hope to do it soon.

**Comment by daweber** [comment]
I don't mind doing a workaround, I'm just having a hard-time figuring out the right steps.

**Comment by daweber** [comment]
In case anyone else comes here looking for an answer, here are the steps that worked for me.

**Step 1 (per ochawkeye):** 

If you manually flip-flop the schedule back to the regular season URL in file ..\nflgame\live.py (uncomment line 68 _CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/ss.xml" & comment out line 75 _CUR_SCHEDULE = http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml")

**Step 2:** run update_sched.py --year 2016 --phase REG

**Step 3:** Manually add [LA, Los Angeles, Rams] to teams table. I also did (per danielcroona):

You should edit the files nfldb/team.py and nflgame/init.py, and add the following line:
['LA', 'Los Angeles', 'Rams', 'Los Angeles Rams'],

On my machine the location for these files are:
/usr/local/lib/python2.7/dist-packages/nfldb/team.py
/usr/local/lib/python2.7/dist-packages/nflgame/init.py

But... I don't know how to get those changes to take effect, hence the manually added part.

**Step 4:** run nfldb-update

**Step 5 (maybe):** revert changes from Step 1 and run nfldb-update again. I think this is what was meant by "flip-flop", but changing it back didn't seam to do anything (presumable because there is no postseason yet).

@BurntSushi Please let me know if any of this is wrong. Also, what would I of had to do to make the changes of step 3 work without manually adding the new team record?

Thanks again, I really love nfldb!
