### ISSUE TITLE
installing nfldb

### ISSUE THREAD

**Issue by GenKakow** [BurntSushi/nfldb#175]
Hi,

Sorry if this is a basic question, but I'm running into some trouble when I get to the step "Installing the nfldb Python module"

I'm attempting this on Ubuntu 16.04.
Running the command pip install nfldb produces the error shown below.  I'm new to Linux and  really have no idea where to begin troubleshooting this. 

Thanks in advance!

```
emil@emil-OptiPlex-390:~/Downloads$ pip2 install nfldb
Collecting nfldb
  Downloading nfldb-0.2.15.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 855kB/s 
Collecting nflgame>=1.2.19 (from nfldb)
  Downloading nflgame-1.2.19.tar.gz (33.0MB)
    100% |████████████████████████████████| 33.0MB 45kB/s 
Collecting psycopg2 (from nfldb)
  Downloading psycopg2-2.6.2.tar.gz (376kB)
    100% |████████████████████████████████| 378kB 2.1MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qR0cGp/psycopg2/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


```

**Comment by BurntSushi** [comment]
`pip` is actually telling you what you need to do. :-) See this line:

> Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.

Try doing `sudo apt-get install libpq-dev` and then retrying the `pip` command.

**Comment by GenKakow** [comment]
Hey, 

Thank you for the quick reply, running those commands worked.

In the future, is there somewhere where I can look up package names when I get a similar error? I'm not how to make the connection from  `postgresql-server-dev-X.Y` to installing   `libpq-dev`other than googling and hoping that someone has asked a similar question. Again, sorry if my terminology is off, really new to this.

**Comment by BurntSushi** [comment]
Hmm. Good question.

The error message is a bit dense and is probably hard to understand if you've never worked with C libraries before. Basically, it says that if you're working with the PostgreSQL server (as in, writing *code* for it, which is pretty specialized and pretty rare), then you should install `postgresql-server-dev-X.Y`. We're definitely not doing that here. `nfldb` uses a PostgreSQL client, with a Python package called `psycopg2`. `pip` will install this package for you. Unfortunately, this package has a dependency on the PostgreSQL C client library, and that's called `libpq-dev` (which is in the error message, "... or libpq-dev for building a client-side application."). `pip` doesn't know how to install that because it's a C library, not a Python library. In other words, it is the *responsibility of your system's package manager* to install `libpq-dev`.

`libpq-dev` in particular refers to the C header files associated with `libpq`, which provides the actual library. `psycopg2` needs *both*. You get `libpq` automatically if you have PostgreSQL installed, but you don't need `libpq-dev` for that so it isn't installed. `psycopg2` needs `libpq-dev` because it needs to compile code against the C header files.

Probably the best thing to do here is to put this error message into our install instructions and explain what you need to do. Writing all the context out above is kind of amazing; there's a lot to unpack in that little error message!

**Comment by BurntSushi** [comment]
Actually, the above is further complicated by the fact that `libpq-dev` is the name of a specific package on a specific Linux distribution. Ubuntu is the most popular, so you're in good company. But on Archlinux for example (the distro I use), those header files are provided by the `postgresql` package.
