### ISSUE TITLE
No 2017 data

### ISSUE THREAD

**Issue by RylandCapital** [BurntSushi/nfldb#286]
hey friends,

**I finally got nfldb-update and nflgame-player-update to work without an error after following other issue posts! --- as seen here for nfldb-update:** (player update also works great no errors)
-------------------------------------------------------------------------------
```
STARTING NFLDB UPDATE AT 2017-11-09 14:49:01.893000
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 1 games...
        Sending batch of data to database.
done.
Updating schedule JSON database...
Last updated: 2017-11-09 19:26:53.581000
done.
Updating schedule for (Regular, 2017, 10)
done.
Closing database connection... done.
FINISHED NFLDB UPDATE AT 2017-11-09 14:49:02.645000
```

**however when I got into python and run this example:**

```
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)

q.game(season_year=2017, season_type='Regular', week=1)
for pp in q.sort('passing_yds').limit(5).as_aggregate():
    print pp.player, `pp.passing_yds`
```
**I do not get any data/prints . If I switch to 2016 or earlier it works great! any idea why 2017 is the only thing I cant get?**

RylandCapital

**Comment by PDGIII** [comment]
Experiencing the same issue.

**Comment by RylandCapital** [comment]
I tried every fix I could get my hands on and I just cant get to 2017 data for any available objects/categories. I found a much easier database of data at 
https://www.suredbits.com/api/ if your interested. i have all stats for all players simply with a pandas read json loop. check it out!

**Comment by PDGIII** [comment]
@ochawkeye submitted a workaround on the nflgame wiki by updating 2017 via the update_sched.py script in your nflgame directory:

`peep@fantasypicks2:# python update_sched.py --year 2017
Last updated: 2017-11-12 18:13:25.282509
Updating (2017, PRE, 0)...
Updating (2017, PRE, 1)...
Updating (2017, PRE, 2)...
Updating (2017, PRE, 3)...
Updating (2017, PRE, 4)...
Updating (2017, REG, 1)...
Updating (2017, REG, 2)...
Updating (2017, REG, 3)...
Updating (2017, REG, 4)...
Updating (2017, REG, 5)...
Updating (2017, REG, 6)...
Updating (2017, REG, 7)...
Updating (2017, REG, 8)...
Updating (2017, REG, 9)...
Updating (2017, REG, 10)...
Updating (2017, REG, 11)...
Updating (2017, REG, 12)...
Updating (2017, REG, 13)...
Updating (2017, REG, 14)...
Updating (2017, REG, 15)...
Updating (2017, REG, 16)...
Updating (2017, REG, 17)...
Updating (2017, POST, 1)...
Updating (2017, POST, 2)...
Updating (2017, POST, 3)...
Updating (2017, POST, 4)...
`

Then

`peep@fantasypicks2:/usr/local/lib/python2.7/dist-packages/nflgame# nfldb-update --update-schedules
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2017-11-12 19:07:52.531585
Connecting to nfldb... done.
Setting timezone to UTC... done.
Updating schedule JSON database...
Last updated: 2017-11-12 19:07:42.908796
done.
Updating all game schedules... Locking write access to tables... done.
`

Mine took a bit, because I'm running it on a not so powerful digital ocean droplet. 

The wiki also has some instructions for dealing with the JAX/LAC changes this season.

**Comment by formido** [comment]
@PDGIII 

Can you link to where on the wiki you got that? I don't see it at first glance. Also, a link to the JAX/LAC instructions, if it's not on the same page, would be helpful.
