### ISSUE TITLE
Has the NFL ever complained about this project?

### ISSUE THREAD

**Issue by dimino** [BurntSushi/nfldb#306]
Curious about if the NFL has ever contacted the maintainer of this project (@BurntSushi) for any reason.  If a person uses this technique to pull game data as the backing code for a web project, will the NFL care?

**Comment by dimino** [comment]
And a follow-up; is that why this project is now unmaintained?

**Comment by BurntSushi** [comment]
> Curious about if the NFL has ever contacted the maintainer of this project (@BurntSushi) for any reason.

No. I don't even know that they are aware of it, but I wouldn't be surprised if they are.

> If a person uses this technique to pull game data as the backing code for a web project, will the NFL care?

This is **not** a question for me. It is a question for a lawyer. Certainly, others have built web sites using this project, but they've been small and mostly for personal use AFAIK. To some extent, you're limited in what you can do because the data is not 100% accurate.

> And a follow-up; is that why this project is now unmaintained?

No. I just don't have time for it and no longer use the project myself. It has been unmaintained for years.
